### ISSUE TITLE
Check necessary changes

### ISSUE THREAD

**Issue by SoupyzInc** [rancslab/carma-config-archive#3]
Compare all 48 file diffs of [carma-config](https://github.com/usdot-fhwa-stol/carma-config/compare/develop...VT-ASIM-LAB:carma-config:develop) between usdot-fhwa-stol and VT-ASIM to see what changes are made and why. Add to this description below.

New addition files:
1. ford_fusion_2017/Dockerfile
2. ford_fusion_2017/SubsystemControllerParams.yaml
3. ford_fusion_2017/VehicleConfigParams.yaml
4. ford_fusion_2017/bridge.yml
5. ford_fusion_2017/build-image.sh
6. ford_fusion_2017/carma.config.js
7. ford_fusion_2017/carma.env
8. ford_fusion_2017/carma_docker.launch
9. ford_fusion_2017/carma_docker.launch.py
10. ford_fusion_2017/carma_rosconsole.conf
11. ford_fusion_2017/docker-compose-background.yml
12. ford_fusion_2017/docker-compose.yml
13. ford_fusion_2017/drivers.launch
14. ford_fusion_2017/drivers.launch.py
15. ford_fusion_2017/hooks/build
16. ford_fusion_2017/hooks/pre_build
17. ford_fusion_2017/system_release.sh
18. ford_fusion_2017_ROS1/Dockerfile
19. ford_fusion_2017_ROS1/VehicleConfigParams.yaml
20. ford_fusion_2017_ROS1/build-image.sh
21. ford_fusion_2017_ROS1/carma.config.js
22. ford_fusion_2017_ROS1/carma.env
23. ford_fusion_2017_ROS1/carma_docker.launch
24. ford_fusion_2017_ROS1/carma_rosconsole.conf
25. ford_fusion_2017_ROS1/docker-compose-background.yml
26. ford_fusion_2017_ROS1/docker-compose.yml
27. ford_fusion_2017_ROS1/drivers.launch
28. ford_fusion_2017_ROS1/hooks/build
29. ford_fusion_2017_ROS1/hooks/pre_build
30. ford_fusion_2017_ROS1/system_release.sh
31. ford_fusion_2017_calibration_folder/vehicle/calibration/LI_IMX390/LI_IMX390_200.ini
32. ford_fusion_2017_calibration_folder/vehicle/calibration/LI_IMX390/LI_IMX390_200.yaml
33. ford_fusion_2017_calibration_folder/vehicle/calibration/identifiers/UniqueVehicleParams.yaml
34. ford_fusion_2017_calibration_folder/vehicle/calibration/lidar_euclidean_cluster_detect/calibration.yaml
35. ford_fusion_2017_calibration_folder/vehicle/calibration/lidar_localizer/ndt_matching/params.yaml
36. ford_fusion_2017_calibration_folder/vehicle/calibration/mpc_follower/calibration.yaml
37. ford_fusion_2017_calibration_folder/vehicle/calibration/naive_motion_predict/calibration.yaml
38. ford_fusion_2017_calibration_folder/vehicle/calibration/ouster/OS1-16_sample.json
39. ford_fusion_2017_calibration_folder/vehicle/calibration/ouster/OS1-64U.json
40. ford_fusion_2017_calibration_folder/vehicle/calibration/points_preprocessor/ray_ground_filter/calibration.yaml
41. ford_fusion_2017_calibration_folder/vehicle/calibration/pure_pursuit/calibration.yaml
42. ford_fusion_2017_calibration_folder/vehicle/calibration/range_vision_fusion/lidar_camera_fl_extrinsics.yaml
43. ford_fusion_2017_calibration_folder/vehicle/calibration/range_vision_fusion/lidar_camera_fl_extrinsics_original.yaml
44. ford_fusion_2017_calibration_folder/vehicle/calibration/range_vision_fusion/lidar_camera_fr_extrinsics.yaml
45. ford_fusion_2017_calibration_folder/vehicle/calibration/range_vision_fusion/lidar_camera_fr_extrinsics_original.yaml
46. ford_fusion_2017_calibration_folder/vehicle/calibration/urdf/carma.urdf
47. ford_fusion_2017_calibration_folder/vehicle/calibration/vision_beyond_track/calibration.yaml

Files Changed:
48. ford_fusion_sehybrid_2019/drivers.launch.py
- 3 new changes in the file

- [ ] ford_fusion_sehybrid_2019/docker-compose.yml
  - [ ] Include the following drivers to the file.
```
 ouster-lidar-driver:
    image: usdotfhwastoldev/carma-ouster-lidar-driver:develop
    container_name: ouster-lidar-driver
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    command: bash -c '. ./devel/setup.bash && export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch /opt/carma/vehicle/config/drivers.launch drivers:=ouster_lidar'

  dataspeed-can-driver:
    image: usdotfhwastoldev/carma-dataspeed-can-driver:develop
    container_name: dataspeed-can-driver
    network_mode: host
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    command: bash -c '. ./devel/setup.bash && export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch /opt/carma/vehicle/config/drivers.launch drivers:=dataspeed_can'

  dataspeed-controller-driver:
    image: usdotfhwastoldev/carma-dataspeed-controller-driver:develop
    container_name: dataspeed-controller-driver
    network_mode: host
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    command: bash -c '. ./devel/setup.bash && export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it.sh localhost:11311 -- roslaunch /opt/carma/vehicle/config/drivers.launch drivers:=dataspeed_controller'
```
